name: sql2
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sqflite: ^1.2.0
  http: ^0.12.2
  html: ^0.14.0+3
  web_scraper: ^0.0.6
  url_launcher: ^5.7.0
  flutter_zoom_drawer: ^1.0.4+1
  flutter_svg: ^0.16.0
  path: ^1.6.4
  # shared_preferences: ^0.4.3
  # firebase_core: ^0.4.0+9
  # firebase_auth: ^0.14.0+5
  # cloud_firestore: ^0.12.9+5 
  # material_floating_search_bar: ^0.2.3
  # flappy_search_bar: ^1.7.2
  floating_search_bar: ^0.3.0
  bezier: ^1.1.5
  flutter_parsed_text: ^1.2.5
  shimmer: ^1.1.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/
    - fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:

    - family: man1
      fonts:
        - asset: fonts/Contrai.ttf
    - family: man2
      fonts:
        - asset: fonts/Lobster-Regular.ttf
    - family: man3
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
    - family: man4
      fonts:
        - asset: fonts/PermanentMarker-Regular.ttf
    - family: man5
      fonts:
        - asset: fonts/KaushanScript-Regular.ttf
    - family: man6
      fonts:
        - asset: fonts/Courgette-Regular.ttf
    - family: man7
      fonts:
        - asset: fonts/YanoneKaffeesatz-VariableFont_wght.ttf
    - family: man8
      fonts:
        - asset: fonts/choice1.ttf
    - family: man9   
      fonts:
        - asset: fonts/chc2.ttf
    - family: man10   
      fonts:
        - asset: fonts/chc3.ttf
    - family: man11  
      fonts:
        - asset: fonts/chc4.ttf
    - family: man12  
      fonts:
        - asset: fonts/chc5.ttf
    - family: man13  
      fonts:
        - asset: fonts/qote.ttf
    - family: man14  
      fonts:
        - asset: fonts/qote.ttf
    - family: man15  
      fonts:
        - asset: fonts/RacingSansOne-Regular.ttf
        
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
